### ISSUE TITLE
입력한 데이터가 정해놓은 칸을 초과하면 다음 줄에 출력하도록 설정

### ISSUE THREAD

**Issue by SonMinWoo** [SonMinWoo/AnsanBladeWind#6]
|      1      |     asd     |     123     |      X      |
|      2      |      qw     |    123943   |      O      |
|      3      |     asd     |     123     |      X      |
|      4      |     sad     |     123     |      X      |
|      5      |     asd     |     123     |      X      |
|      6      | a1aa2aaa3aaaa4aaaaa5aaaaaa6aaaaaaa7aaaaaaaa8| 111121113111141111151111116111111171111111181111111119|      X      |

현재는 위와 같이 데이터가 출력됩니다. ( id : 2는 자동으로 칸에 맞춰집니다.)
위 데이터를 아래와 같이 출력되게 해 주세요.

|      1      |     asd     |     123     |      X      |
|      2      |      qw     |    123943   |      O      |
|      3      |     asd     |     123     |      X      |
|      4      |     sad     |     123     |      X      |
|      5      |     asd     |     123     |      X      |
|      6      | a1aa2aa  | 111121  |       X      |
               |  a3aaaa4 | 113111  |
               | aaaaa5a  | 411115  |
               | aaaa6aa  | 111116  |
               | aaaa7aa  | 111171  |
               | aaaaa8    | 111118 |       
                                | 111111 |
                                | 9           |

**Comment by Keunmo** [comment]
#9
