### ISSUE TITLE
지우기 기능 추가

### ISSUE THREAD

**Issue by SonMinWoo** [SonMinWoo/AnsanBladeWind#7]
1. 지우고 싶은 id를 지우는 기능 추가 (하나 뿐만이 아니라 여러개의 contents를 지울 수 있도록 해주세요)
2. 전체 contents 지우는 기능 추가

**Comment by Keunmo** [comment]
https://github.com/SonMinWoo/AnsanBladeWind/commit/d7ed5ef057fdc5eea6475209c5860244246938f9
